// SPDX-License-Identifier: MIT
// libs/crypto/src/crypto.zig
// Pure-Zig crypto functions. No gawk dependency.
const std = @import("std");

const Sha256 = std.crypto.hash.sha2.Sha256;
const HmacSha256 = std.crypto.auth.hmac.sha2.HmacSha256;
const argon2 = std.crypto.pwhash.argon2;
const Ecdsa = std.crypto.sign.ecdsa.EcdsaP256Sha256;
const b64 = std.base64.url_safe_no_pad;

/// Returns lowercase hex string of SHA-256 hash. Caller owns nothing (stack allocated).
pub fn sha256(data: []const u8) [64]u8 {
    var hash: [Sha256.digest_length]u8 = undefined;
    Sha256.hash(data, &hash, .{});
    return bytesToHex(&hash);
}

/// Returns lowercase hex string of HMAC-SHA-256. Caller owns nothing (stack allocated).
pub fn hmacSha256(key: []const u8, data: []const u8) [64]u8 {
    var mac: [HmacSha256.mac_length]u8 = undefined;
    HmacSha256.create(&mac, data, key);
    return bytesToHex(&mac);
}

/// Hashes password using Argon2id (salt auto-generated by strHash).
/// Caller owns returned slice (allocator.free).
/// Requires std.Io for entropy (use std.testing.io in tests).
pub fn argon2idHash(allocator: std.mem.Allocator, password: []const u8, io: std.Io) ![]u8 {
    var buf: [256]u8 = undefined;
    const params = argon2.Params{ .t = 2, .m = 65536, .p = 1 };
    const hash = try argon2.strHash(password, .{ .allocator = allocator, .params = params }, &buf, io);
    return allocator.dupe(u8, hash);
}

/// Verifies a password against an Argon2id hash string.
/// Requires std.Io for entropy (use std.testing.io in tests).
pub fn argon2idVerify(allocator: std.mem.Allocator, hash: []const u8, password: []const u8, io: std.Io) bool {
    argon2.strVerify(hash, password, .{ .allocator = allocator }, io) catch return false;
    return true;
}

pub const EcdsaKeyPair = struct {
    secret_key_bytes: [Ecdsa.SecretKey.encoded_length]u8,
    public_key_bytes: [Ecdsa.PublicKey.uncompressed_sec1_encoded_length]u8,
};

/// Generate a new P-256 key pair.
/// Requires std.Io for entropy (use std.testing.io in tests).
pub fn ecdsaGenKey(io: std.Io) EcdsaKeyPair {
    const kp = Ecdsa.KeyPair.generate(io);
    return .{
        .secret_key_bytes = kp.secret_key.toBytes(),
        .public_key_bytes = kp.public_key.toUncompressedSec1(),
    };
}

/// Sign data with a P-256 secret key (raw bytes). Returns base64url-encoded signature.
/// Caller owns returned slice.
pub fn ecdsaSign(allocator: std.mem.Allocator, secret_key_bytes: []const u8, data: []const u8) ![]u8 {
    if (secret_key_bytes.len != Ecdsa.SecretKey.encoded_length) return error.InvalidKeyLength;
    const sk = try Ecdsa.SecretKey.fromBytes(secret_key_bytes[0..Ecdsa.SecretKey.encoded_length].*);
    const kp = try Ecdsa.KeyPair.fromSecretKey(sk);
    const sig = try kp.sign(data, null);
    const sig_bytes = sig.toBytes();
    const encoded_len = b64.Encoder.calcSize(sig_bytes.len);
    const out = try allocator.alloc(u8, encoded_len);
    _ = b64.Encoder.encode(out, &sig_bytes);
    return out;
}

/// Verify a base64url-encoded P-256 signature. Returns false on any error.
pub fn ecdsaVerify(allocator: std.mem.Allocator, public_key_bytes: []const u8, data: []const u8, b64_sig: []const u8) bool {
    if (public_key_bytes.len != Ecdsa.PublicKey.uncompressed_sec1_encoded_length) return false;
    const pk = Ecdsa.PublicKey.fromSec1(public_key_bytes) catch return false;
    const sig_len = b64.Decoder.calcSizeForSlice(b64_sig) catch return false;
    const sig_bytes = allocator.alloc(u8, sig_len) catch return false;
    defer allocator.free(sig_bytes);
    b64.Decoder.decode(sig_bytes, b64_sig) catch return false;
    if (sig_bytes.len != Ecdsa.Signature.encoded_length) return false;
    const sig = Ecdsa.Signature.fromBytes(sig_bytes[0..Ecdsa.Signature.encoded_length].*);
    sig.verify(data, pk) catch return false;
    return true;
}

fn bytesToHex(bytes: []const u8) [64]u8 {
    const chars = "0123456789abcdef";
    var result: [64]u8 = undefined;
    for (bytes, 0..) |b, i| {
        result[i * 2] = chars[b >> 4];
        result[i * 2 + 1] = chars[b & 0xf];
    }
    return result;
}
